name: 💡 Suggestion
description: "Suggest a new feature or an improvement."
labels:
- "Enhancement"
body:
- type: markdown
  attributes:
    value: |-     
      Please fill this form carefully and provide the requested details. Thank you for contributing to the project.
      
      Suggest changes that would benefit as many users as possible, not just specific situations.

- type: textarea
  attributes:
    label: "Description"
    description: "Describe the new feature or improvement you suggest."
  validations:
    required: true
